export const siteList = [
    {
        // 图片识别 看有没有免费的
        name: '动漫花园',
        site: "https://u2.dmhy.org",
        siteType: 'U2',
        targetUrl: "https://u2.dmhy.org/showup.php"
    }, {
        // 一次性按钮 不跳转页面 签到信息刷新后消失再也不见 刷新页面不再显示签到获得数字
        name: '海胆',
        site: "https://www.haidan.video/",
        siteType: 'HaiDan',
        targetUrl: "https://www.haidan.video/"
    }, {
        // 一次性按钮 会跳转页面 签到信息弹窗显示 关闭弹窗消失 刷新页面再也不见
        name: '学校',
        site: "https://pt.btschool.club/",
        siteType: 'btSchool',
        targetUrl: "https://pt.btschool.club/index.php?action=addbonus"
    }, {
        // 点击 然后弹窗
        name: '听听歌',
        site: "https://totheglory.im/",
        siteType: 'ttg',
        targetUrl: "https://totheglory.im/"
    },
    {
        name: '观众',
        site: "https://audiences.me",
        siteType: 'NexusPHP',
        targetUrl: "https://audiences.me/attendance.php"
    }, {
        name: '大青虫',
        site: "https://cyanbug.net",
        siteType: 'NexusPHP',
        targetUrl: "https://cyanbug.net/attendance.php"
    }, {
        name: '蟹黄堡',
        site: "https://crabpt.vip",
        siteType: 'NexusPHP',
        targetUrl: "https://crabpt.vip/attendance.php"
    }, {
        name: '青蛙',
        site: "https://qingwapt.com",
        siteType: 'NexusPHP',
        targetUrl: "https://qingwapt.com/attendance.php"
    }, {
        name: '末日',
        site: "https://pt.agsvpt.cn",
        siteType: 'NexusPHP',
        targetUrl: "https://pt.agsvpt.cn/attendance.php"
    }, {
        name: '红豆饭',
        site: "https://hdfans.org/",
        siteType: 'NexusPHP',
        targetUrl: "https://hdfans.org/attendance.php"
    }, {
        // 需要等待签到结果
        name: '麒麟',
        site: "https://hdkyl.in/",
        siteType: 'NexusPHP',
        targetUrl: "https://www.hdkyl.in/attendance.php"
    }, {
        name: 'carPT',
        site: "https://carpt.net/",
        siteType: 'NexusPHP',
        targetUrl: "https://carpt.net/attendance.php"
    }, {
        name: '肉丝',
        site: "https://rousi.zip/",
        siteType: 'NexusPHP',
        targetUrl: "https://rousi.zip/attendance.php"
    }, {
        // 需要等待签到结果
        name: '优堡',
        site: "https://ubits.club/",
        siteType: 'NexusPHP',
        targetUrl: "https://ubits.club/attendance.php"
    }, {
        // 可能有二次验证
        name: '杜比',
        site: "https://hddolby.com/",
        siteType: 'NexusPHP',
        targetUrl: "https://www.hddolby.com/attendance.php"
    }, {
        name: '家园',
        site: "https://hdhome.org/",
        siteType: 'NexusPHP',
        targetUrl: "https://hdhome.org/attendance.php"
    }, {
        name: '我堡',
        site: "https://ourbits.club/",
        siteType: 'NexusPHP',
        targetUrl: "https://ourbits.club/attendance.php"
    }, {
        name: 'RailgunPT',
        site: "https://bilibili.download/",
        siteType: 'NexusPHP',
        targetUrl: "https://bilibili.download/attendance.php"
    }, {
        name: '憨憨',
        site: "https://hhanclub.top/",
        siteType: 'HanHan',
        targetUrl: "https://hhanclub.top/attendance.php"
    }, {
        name: '龟站',
        site: "https://kamept.com/",
        siteType: 'NexusPHP',
        targetUrl: "https://kamept.com/attendance.php"
    }];

